### ISSUE TITLE
Does not work with minimal execution outputs

### ISSUE THREAD

**Issue by Monnoroch** [buildbarn/bb-browser#12] opened 2019-06-20 00:36 UTC
When running build with `--experimental_remote_download_outputs=minimal`, bazel prints out a `/build_events/bb-event-service/$ID` link, but it can't be opened in the browser.

Error: `rpc error: code = InvalidArgument desc = Event with ID "progress: <\n  opaque_count: 257\n>\n" was not expected`.

Same exact build with full outputs (the default) is working just fine.

**Comment by Monnoroch** [comment] 2019-06-20 01:54
Checked that it doesn't happen all the time, but quite often. Retrying helps.

**Comment by mickael-carl** [comment] 2019-08-02 18:44
Just managed to reproduce this and indeed it seems fairly random. I'll try to find out what's happening there

**Comment by leosh64** [comment] 2020-01-03 06:08
We also experience this issue from time to time... Did you find anything regarding the cause or how to fix it?

**Comment by EdSchouten** [comment] 2020-01-04 00:33
Most Buildbarn components recently became maintained again. Unfortunately, I will not be maintaining bb-event-service (and BES related code in bb-browser) actively. I am really hoping someone in the community will step up to maintain it going forward. This can either be done as part of the Buildbarn project or externally.

Now to get back to the issue at hand. The Build Event Stream contains a series of events. bb-event-service will store them in the CAS literally and relies on bb-browser to render them. Before doing so, bb-browser will first convert the events into a tree. What’s going wrong here is that bb-browser either encounters an event it doesn’t support, or it obtains an event type that is added to an unexpected part of the tree. bb-browser will need to be extended to process those events properly.

**Comment by leosh64** [comment] 2020-01-04 12:59
Hello, what a pity that so far there are no plans for further maintenance of BES... 

How much effort is it to extend bb-browser to support additional events? Can you give an estimate? Meanwhile, would it be possible to create a temporary quick-fix solution, e.g. just ignoring unexpected events or replacing them with some placeholder ("not-yet-supported") without crashing, so that at least the remainder can be processed and shown?

**Comment by EdSchouten** [comment] 2020-03-14 13:12
It's not that much of an effort to add support for additional events, but it's just that bb-browser also  doesn't provide any facilities to make displaying quick (by aggregating data as it comes in), nor is it able to cross reference between build event streams ("Please show me past builds for the same target").

I'm marking this as closed, as we are going to remove support for BES altogether. We hope other folks in the community are working on solving this problem for us.

**Closed as completed by EdSchouten** 2020-03-14 13:12 UTC
Labels: bug
